// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5sdbITWDl-NcTI7-epcq-UfacybbkxUE',
    appId: '1:2355280728:web:b066b72f611560b7e3832d',
    messagingSenderId: '2355280728',
    projectId: 'dongwoo-zookeeper',
    authDomain: 'dongwoo-zookeeper.firebaseapp.com',
    storageBucket: 'dongwoo-zookeeper.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdE5S_sb13OaFWSjTmQHenp0sfPTfRY7s',
    appId: '1:2355280728:android:074d031d1a111c9be3832d',
    messagingSenderId: '2355280728',
    projectId: 'dongwoo-zookeeper',
    storageBucket: 'dongwoo-zookeeper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh5Ag_xZtPF4kh6Wt2urAw9NAR3K8_REg',
    appId: '1:2355280728:ios:5dc5ecbfd5535673e3832d',
    messagingSenderId: '2355280728',
    projectId: 'dongwoo-zookeeper',
    storageBucket: 'dongwoo-zookeeper.appspot.com',
    iosBundleId: 'co.nomadcoders.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh5Ag_xZtPF4kh6Wt2urAw9NAR3K8_REg',
    appId: '1:2355280728:ios:3d537a80289519dde3832d',
    messagingSenderId: '2355280728',
    projectId: 'dongwoo-zookeeper',
    storageBucket: 'dongwoo-zookeeper.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
